# fly.toml app configuration file generated for footy-live on 2025-07-05T16:57:36+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'footy-live'
primary_region = 'syd'
kill_signal = 'SIGTERM'

[build]

[env]
PHX_HOST = 'foomtbal.sadcloud.co'
PORT = '8080'
FOOTY_LIVE_DB_PATH = '/data'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[http_service.concurrency]
type = 'connections'
hard_limit = 1000
soft_limit = 1000

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1

[[mounts]]
source = "data"
destination = "/data"
