apiVersion: v1
kind: ServiceAccount
metadata:
  name: foomtbal
  namespace: foomtbal
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: foomtbal-endpoint-list
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: foomtbal-endpoint-list
subjects:
  - kind: ServiceAccount
    name: foomtbal
    namespace: foomtbal
