apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: foomtbal
spec:
  replicas: 1
  serviceName: foomtbal
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

  template:
    spec:
      serviceAccount: foomtbal
      setHostnameAsFQDN: true
      containers:
        - name: application
          image: foomtbal
          livenessProbe:
            initialDelaySeconds: 5
            httpGet:
              port: 80
              path: /healthz
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              port: 80
              path: /healthz
          envFrom:
            - secretRef:
                name: foomtbal-secret
            - configMapRef:
                name: foomtbal-config

          volumeMounts:
            - name: data
              mountPath: /data
          env:
            - name: PORT
              value: "80"
            - name: FOOTY_LIVE_DB_PATH
              value: /data

          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
